database:
  connection:
    jdbcUrl: jdbc:h2:~/temp
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  connectionPool:
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 30000
    connectionTimeout: 20000
    maxLifetime: 1800000
