CREATE TABLE CUSTOMERS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ORDERS (
    ID BIGSERIAL PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AMOUNT NUMERIC(10, 2) DEFAULT 0.00,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE PRODUCTS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE NUMERIC(10, 2) NOT NULL
);

CREATE TABLE ORDER_PRODUCTS (
    ORDER_ID BIGINT,
    PRODUCT_ID BIGINT,
    QUANTITY INT DEFAULT 1,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);
